library(shiny)
library(plotly)
library(shinyWidgets)
library(shinyjs)
library(reactable)
library(ggplot2)
library(leaflet)
library(shinythemes)
library(tidyverse)
library(tidycensus)
library(kableExtra)
library(ggthemes)
library(dplyr)
options(tigris_use_cache = TRUE)
library(priceR)

source("my_ui.R")
source("my_server.R")

shiny::shinyApp(ui = ui, server = server)